"""Remove progress column from reporting_analyses

Revision ID: 01a0880e26c4
Revises: aca783b90238
Create Date: 2025-07-17 16:33:26.384031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a0880e26c4'
down_revision: Union[str, None] = 'aca783b90238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reporting_analyses', 'progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reporting_analyses', sa.Column('progress', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###