"""Add anthropic_file_id to files table

Revision ID: 0f015d837733
Revises: f896f491baa8
Create Date: 2025-07-13 19:19:35.970366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f015d837733'
down_revision: Union[str, None] = 'f896f491baa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('anthropic_file_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'anthropic_file_id')
    # ### end Alembic commands ###