"""Remove department field from files table

Revision ID: 274b8a8d57de
Revises: 8fa5592472a7
Create Date: 2025-07-13 21:58:51.359460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '274b8a8d57de'
down_revision: Union[str, None] = '8fa5592472a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###