"""Remove unused columns from reporting_analyses

Revision ID: 2d5a970729aa
Revises: 274b8a8d57de
Create Date: 2025-07-17 16:21:01.357792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d5a970729aa'
down_revision: Union[str, None] = '274b8a8d57de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('analyses_celery_task_id_key', 'reporting_analyses', type_='unique')
    op.drop_column('reporting_analyses', 'celery_task_id')
    op.drop_column('reporting_analyses', 'progress_message')
    op.drop_column('reporting_analyses', 'error_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reporting_analyses', sa.Column('error_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('reporting_analyses', sa.Column('progress_message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reporting_analyses', sa.Column('celery_task_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('analyses_celery_task_id_key', 'reporting_analyses', ['celery_task_id'])
    # ### end Alembic commands ###