"""add_realized_gain_columns

Revision ID: 2db3a104b7cf
Revises: f0645e90f0b4
Create Date: 2026-01-29 16:37:37.908515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db3a104b7cf'
down_revision: Union[str, None] = 'f0645e90f0b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('realized_gain_usd', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('assets', sa.Column('realized_gain_eur', sa.Numeric(precision=20, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'realized_gain_eur')
    op.drop_column('assets', 'realized_gain_usd')
    # ### end Alembic commands ###