"""add_real_estate_return_columns

Revision ID: 302141b07324
Revises: fcfab0cba93d
Create Date: 2026-01-19 20:38:44.434423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302141b07324'
down_revision: Union[str, None] = 'fcfab0cba93d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_estate_assets', sa.Column('total_asset_return_usd', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('real_estate_assets', sa.Column('total_asset_return_eur', sa.Numeric(precision=10, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('real_estate_assets', 'total_asset_return_eur')
    op.drop_column('real_estate_assets', 'total_asset_return_usd')
    # ### end Alembic commands ###