"""Add input_tokens and output_tokens to reporting_analyses

Revision ID: 435b7602e996
Revises: 6383cc244e68
Create Date: 2025-07-19 16:05:01.467903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435b7602e996'
down_revision: Union[str, None] = '6383cc244e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reporting_analyses', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('reporting_analyses', sa.Column('output_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reporting_analyses', 'output_tokens')
    op.drop_column('reporting_analyses', 'input_tokens')
    # ### end Alembic commands ###