"""Remove unused fields from files table

Revision ID: 8fa5592472a7
Revises: 0f015d837733
Create Date: 2025-07-13 21:36:48.682045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fa5592472a7'
down_revision: Union[str, None] = '0f015d837733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'processing_started_at')
    op.drop_column('files', 'processing_completed_at')
    op.drop_column('files', 'updated_at')
    op.drop_column('files', 'error_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('processing_completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('processing_started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###