"""Consolidate reporting modules into single module

Revision ID: 9d0621f8a4b9
Revises: 1178c10e0997
Create Date: 2025-07-05 18:56:30.717184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0621f8a4b9'
down_revision: Union[str, None] = '1178c10e0997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###