"""Remove agent_type column from reporting_analyses

Revision ID: aca783b90238
Revises: 2d5a970729aa
Create Date: 2025-07-17 16:28:39.188538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aca783b90238'
down_revision: Union[str, None] = '2d5a970729aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reporting_analyses', 'agent_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reporting_analyses', sa.Column('agent_type', postgresql.ENUM('EXCEL_ANALYZER', 'CHART_RECOMMENDER', 'DATA_CLASSIFIER', 'INSIGHT_GENERATOR', name='agenttype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###