"""Add portfolio tables - 3 essential tables only

Revision ID: e47ac02c7b04
Revises: 435b7602e996
Create Date: 2025-09-15 23:58:52.182194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e47ac02c7b04'
down_revision: Union[str, None] = '435b7602e996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('ownership_holding_entity', sa.String(length=100), nullable=False),
    sa.Column('asset_group', sa.String(length=100), nullable=False),
    sa.Column('asset_sub_group', sa.String(length=100), nullable=True),
    sa.Column('asset_type', sa.String(length=100), nullable=False),
    sa.Column('asset_name', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('asset_identifier', sa.String(length=100), nullable=True),
    sa.Column('asset_status', sa.String(length=50), nullable=True),
    sa.Column('broker_asset_manager', sa.String(length=200), nullable=True),
    sa.Column('denomination_currency', sa.String(length=3), nullable=False),
    sa.Column('initial_investment_date', sa.Date(), nullable=True),
    sa.Column('number_of_shares', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('avg_purchase_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('total_investment_commitment', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('paid_in_capital', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('asset_level_financing', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pending_investment', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('current_share_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('estimated_asset_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_asset_return', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assets_entity', 'assets', ['ownership_holding_entity'], unique=False)
    op.create_index('idx_assets_group', 'assets', ['asset_group'], unique=False)
    op.create_index('idx_assets_name', 'assets', ['asset_name'], unique=False)
    op.create_index('idx_assets_status', 'assets', ['asset_status'], unique=False)
    op.create_table('real_estate_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('cost_original_asset', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('estimated_capex_budget', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pivert_development_fees', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('estimated_total_cost', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('capex_invested', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_investment_to_date', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('equity_investment_to_date', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pending_equity_investment', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('estimated_capital_gain', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_index('idx_real_estate_asset', 'real_estate_assets', ['asset_id'], unique=False)
    op.create_table('structured_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('annual_coupon', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('coupon_payment_frequency', sa.String(length=50), nullable=True),
    sa.Column('next_coupon_review_date', sa.String(length=50), nullable=True),
    sa.Column('next_principal_review_date', sa.Date(), nullable=True),
    sa.Column('final_due_date', sa.Date(), nullable=True),
    sa.Column('redemption_type', sa.String(length=50), nullable=True),
    sa.Column('underlying_index_name', sa.String(length=200), nullable=True),
    sa.Column('underlying_index_code', sa.String(length=50), nullable=True),
    sa.Column('strike_level', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('underlying_index_level', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('performance_vs_strike', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('effective_strike_percentage', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('note_leverage', sa.String(length=50), nullable=True),
    sa.Column('capital_protection', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('capital_protection_barrier', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('coupon_protection_barrier_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('coupon_protection_barrier_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_index('idx_structured_notes_asset', 'structured_notes', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_structured_notes_asset', table_name='structured_notes')
    op.drop_table('structured_notes')
    op.drop_index('idx_real_estate_asset', table_name='real_estate_assets')
    op.drop_table('real_estate_assets')
    op.drop_index('idx_assets_status', table_name='assets')
    op.drop_index('idx_assets_name', table_name='assets')
    op.drop_index('idx_assets_group', table_name='assets')
    op.drop_index('idx_assets_entity', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###