"""remove_redundant_return_columns_from_real_estate

Revision ID: f0645e90f0b4
Revises: 302141b07324
Create Date: 2026-01-19 21:12:23.285440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0645e90f0b4'
down_revision: Union[str, None] = '302141b07324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('real_estate_assets', 'total_asset_return_eur')
    op.drop_column('real_estate_assets', 'total_asset_return_usd')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_estate_assets', sa.Column('total_asset_return_usd', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True))
    op.add_column('real_estate_assets', sa.Column('total_asset_return_eur', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True))
    # ### end Alembic commands ###