"""Add portfolio_reports table

Revision ID: fcfab0cba93d
Revises: b5c8a2d1e3f4
Create Date: 2026-01-04 00:05:12.794518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcfab0cba93d'
down_revision: Union[str, None] = 'b5c8a2d1e3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.Enum('SINGLE_DATE', 'ALL_DATES', name='reportscope'), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('entity_filter', sa.String(length=100), nullable=True),
    sa.Column('asset_type_filter', sa.String(length=100), nullable=True),
    sa.Column('holding_company_filter', sa.String(length=100), nullable=True),
    sa.Column('user_prompt', sa.Text(), nullable=True),
    sa.Column('research_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='reportstatus'), nullable=False),
    sa.Column('agent_version', sa.String(length=20), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_assets_group', table_name='assets')
    op.create_index('idx_assets_group', 'assets', ['asset_group'], unique=False)
    op.create_index('idx_assets_managing_entity', 'assets', ['managing_entity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_assets_managing_entity', table_name='assets')
    op.drop_index('idx_assets_group', table_name='assets')
    op.create_index('idx_assets_group', 'assets', ['managing_entity'], unique=False)
    op.drop_table('portfolio_reports')
    # ### end Alembic commands ###